export default {
    nodes: [
        {name: 'root', main: true, value: 400, color: 0},
        {name: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', value:300, color: 1},
        {name: 'Work', value:300, color: 1},
        {name: 'Fashion', value:300, color: 1},
        {name: 'Vacation', value:300, color: 1},
        {name: 'bo', value:200, color: 2},
        {name: 'bryan', value:200, color: 2},
        {name: 'jovan', value:200, color: 2},
        {name: 'brayton', value:200, color: 2},
        {name: 'california', value:200, color: 2},
        {name: 'new york', value:200, color: 2},
        {name: 'las vegas', value:200, color: 2},
        {name: 'codesmith', value:200, color: 2},
        {name: 'chinatown', value:200, color: 3},
        {name: 'extra1', value:200, color: 4, notLinked: true},
        {name: 'extra2', value:200, color: 4, notLinked: true},
        {name: 'extra3', value:200, color: 4, notLinked: true},
    ],
    links: [
        {source: 'root', target: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', color: 0},
        {source: 'root', target: 'Vacation', color: 0},
        {source: 'root', target: 'Fashion', color: 0},
        {source: 'root', target: 'Work', color: 0},
        {source: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', target: 'bo', color: 1},
        {source: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', target: 'brayton', color: 1},
        {source: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', target: 'bryan', color: 1},
        {source: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', target: 'jovan', color: 1},
        {source: 'CheckoutGiftCardRemovePayloadCheckoutGiftCardRemovePayload', target: 'Fashion', color: 1},
        {source: 'Vacation', target: 'california', color: 1},
        {source: 'Vacation', target: 'new york', color: 1},
        {source: 'Vacation', target: 'las vegas', color: 1},
        {source: 'Work', target: 'codesmith', color: 1},
        {source: 'jovan', target: 'codesmith', color: 2},
        {source: 'bo', target: 'codesmith', color: 2},
        {source: 'brayton', target: 'codesmith', color: 2},
        {source: 'bryan', target: 'codesmith', color: 2},
        {source: 'codesmith', target: 'chinatown', color: 2},
    ]
}