version: '3'
services:
  dev:
    image: "novaintrospection/nova-dev"
    container_name: "nova-dev-hot"
    ports: 
    - "8080:8080"
    - "3000:3000"
    volumes:
    - ./:/usr/src/app
    - node_modules:/usr/src/app/node_modules
    command: npm run dev:hot
    depends_on: 
    - redis
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: ["redis-server"]
volumes: 
  node_modules: {}